# Generated by Django 4.0.4 on 2023-01-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='grade',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
